# 모델명 검색색
model_name : "meta-llama/Meta_Llama-3.1-8B-Instruct"

# 학습 데이터 사용 경로
dataset_path : '.' 

#시퀀스 최대 길이
max_seq_length : 512  

# 모델 학습 과정에서 생성되는 학습 모델
output_dir : "./llama-3.1-korean-8b-hf-20-epoch" 

# 로그와 성능 지표 플랫폼 
report_to : "mlflow" 

# 신경망의 가중치 설정(전체적으로 0.00001 ~ 0.00005)
learning_rate : 0.00005 

# 학습률 스케줄러
lr_scheduler_type : "linear" 

# 전체 데이터셋 학습 주기
num_train_epochs : 5 

# GPU에서 학습할 데이터 개수
per_device_train_batch_size : 2 

#각 디바이스에서 처리할 데이터 개수
per_device_eval_batch_size : 2 

# 배치 크기 효과
gradient_accumulation_steps : 4 

# 모델 학습에 사용할 최적화 알고리즘
optim : "adamw_torch_fused"

# 로그를 기록할 주기를 스텝 단위로 설정
logging_steps : 10

# 모델 체크포인트 저장
save_strategy : "epoch"

# 과적합 방지 및 성능 향상
weight_decay : 0.01

# 클리핑의 입곗값을 지정
max_grad_norm : 0.5

#학습률 웜업 기법
warmup_ratio : 0.03

# bfloat16의 정밀도 사용
bf16 : ture

# tf32형식 활성화
tf32 : ture

# 그레이디언트 체크포인팅 기법 활성화
gradient_checkpointing : ture

# GPU 효율 증가
fsdp : "full_shard auto_wrap"

# 분산처리의 효율성 증가
fsdp_config :
  backward_prefetch : "backward_pre"
  forward_prefetch : "false"
  use_orig_params : "false"